<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductNodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $product_nodes = [

            [
                // comuniti Website
                'main_listing_node' => '.recipe_prod_add_to_cart',
                'title' => '.c-product__name',
                'description' => '',
                'brand' => '.c-product__type',
                'price' => '.c-product__price .price',
                'unit_price' => '.c-product__price .c-product__price-perkg',
                'discount' => '.c-product__card-section .c-badge__text',
                'image' => '.c-product__photo',
                'image_url' => '',
                'rating' => '.favorites-block .favorites-count',
                'product_link' => '.c-product__link-wrapper.favorites-count_font',
                'product_url' => '',
                'website_id' => '1',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '',
                'str_replace' => '',
                'replace_with' => '',
                'append_str' => '',
            ],
            [
                // https://goodafter.com/
                'main_listing_node' => '.item.ajax_block_product',
                'title' => '.product-box .product-name',
                'description' => '',
                'brand' => '.marca-produto',
                'price' => '.product-box .product-info .content_price .price.new, .product-carousel-box .group-box .content_price .price.new',
                'unit_price' => 'span.product-unit-price.sub',
                'discount' => 'span.price-percent-reduction',
                'image' => '.product-box .preview .product-image img',
                'image_url' => '',
                'rating' => '',
                'product_link' => '.product-image.image_blur',
                'product_url' => '',
                'website_id' => '2',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '',
                'str_replace' => '',
                'replace_with' => '',
                'append_str' => '',
            ],
            [
                //https://www.auchan.pt/Frontoffice/
                'main_listing_node' => '.view-grid .product-item',
                'title' => '.product-item-header h3',
                'description' => '',
                'brand' => '.product-item-header .product-item-brand',
                'price' => '.product-item-price',
                'unit_price' => '.product-item-quantity-price',
                'discount' => '',
                'image' => '.product-item-image',
                'image_url' => '',
                'rating' => '',
                'product_link' => '.product-item-header a',
                'product_url' => 'https://www.auchan.pt',
                'website_id' => '3',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '',
                'str_replace' => '',
                'replace_with' => '',
                'append_str' => '',
            ],
            [
                //https://www.continente.pt/pt-pt/public/Pages/homepage.aspx
                'main_listing_node' => '.productItem',
                'title' => '.productItem .productBox .containerDescription .title a',
                'description' => '',
                'brand' => '.productItem .productBox .containerDescription .type',
                'price' => '.productItem .productBox .containerIcons .discountMessage .priceFirstRow, .productItem .productBox .containerPrice .priceFirstRow',
                'unit_price' => '',
                'discount' => '',
                'image' => '.productItem .productBox .containerImage img',
                'image_url' => '',
                'rating' => '',
                'product_link' => '.productItem .productBox .containerDescription .title a',
                'product_url' => '',
                'website_id' => '4',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '',
                'str_replace' => '',
                'replace_with' => '',
                'append_str' => '',
            ],
            [
                // https://www.spar.pt/
                'main_listing_node' => '.item-box',
                'title' => '.item-box .product-title a',
                'description' => '',
                'brand' => '',
                'price' => '.item-box .actual-price',
                'unit_price' => '',
                'discount' => '',
                'image' => '.item-box .picture a img',
                'image_url' => 'https://www.spar.pt',
                'rating' => '.item-box .rating',
                'product_link' => '.item-box .product-title a',
                'product_url' => '',
                'website_id' => '5',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '',
                'str_replace' => '',
                'replace_with' => '',
                'append_str' => '',
            ],
            [
                //  https://www.celeiro.pt
                'main_listing_node' => '.page-products .products-grid li.product-item',
                'title' => '.product-item-link',
                'description' => 'longDescription',
                'brand' => '.brand',
                'price' => '.price',
                'unit_price' => '.apresentacao',
                'discount' => '',
                'image' => 'IMG.product-image-photo',
                'image_url' => '',
                'rating' => '',
                'product_link' => 'a',
                'product_url' => '',
                'website_id' => '6',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '',
                'str_replace' => '',
                'replace_with' => '',
                'append_str' => '',
            ],
            [
                // https://www.froiz.pt/
                'main_listing_node' => '.una-categoria-lista li',
                'title' => '.of_nombre',
                'description' => '',
                'brand' => '',
                'price' => '.of_precio_rebajado',
                'unit_price' => '.of_precio_peso',
                'discount' => '',
                'image' => '.of_imagen',
                'image_url' => '',
                'rating' => '',
                'product_link' => '.of_link',
                'product_url' => '',
                'website_id' => '7',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '',
                'str_replace' => '',
                'replace_with' => '',
                'append_str' => '',
            ],
            [
                // https://www.e-leclerc.pt/
                'main_listing_node' => '.produtos_coluna_cont',
                'title' => '.produtos_nome',
                'description' => '',
                'brand' => '.produtos_marca_texto',
                'price' => '.div_preco',
                'unit_price' => '.listagem_produto_preco_peq',
                'discount' => '.produtos_campanha_valor',
                'image' => 'img',
                'image_url' => '',
                'rating' => '',
                'product_link' => '.produtos_destaque a',
                'product_url' => '',
                'website_id' => '8',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '',
                'str_replace' => '',
                'replace_with' => '',
                'append_str' => '',
            ],

            [
                //  https://www.mercadao.pt
                'main_listing_node' => '',
                'title' => '_source,firstName',
                'description' => '',
                'brand' => '_source,brand,name',
                'price' => '_source,buyingPrice',
                'unit_price' => '_source,unitPrice',
                'discount' => '',
                'image' => '_source,sku',
                'image_url' => 'https://res.cloudinary.com/fonte-online/image/upload/c_fill,h_300,q_auto,w_300/v1/PDO_PROD/',
                'rating' => '',
                'product_link' => '_source,slug',
                'product_url' => 'https://mercadao.pt/store/pingo-doce/product/',
                'website_id' => '9',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '',
                'str_replace' => '300',
                'replace_with' => '600',
                'append_str' => '_1',
            ],
            [
                //  https://www.lidl.pt
                'main_listing_node' => 'article.product.product--tile',
                'title' => '.product--tile .product__title',
                'description' => '',
                'brand' => '',
                'price' => '.pricebox__price',
                'unit_price' => '.pricebox__basic-quantity',
                'discount' => '',
                'image' => 'img.lazyload, img.lazyloaded, img.lazyloading',
                'image_url' => '',
                'rating' => '',
                'product_link' => '.product--tile .product__body',
                'product_url' => 'https://www.lidl.pt/',
                'website_id' => '10',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '',
                'str_replace' => '',
                'replace_with' => '',
                'append_str' => '',
            ],

            [
                //  https://www.bolama.pt
                'main_listing_node' => 'li',
                'title' => 'li div p',
                'description' => '',
                'brand' => '',
                'price' => 'li div div div,li div div div div,li div div div div:nth-child(2)',
                'unit_price' => '',
                'discount' => '',
                'image' => 'img',
                'image_url' => 'https://www.bolama.pt/',
                'rating' => '',
                'product_link' => '',
                'product_url' => 'http://www.bolama.pt/index.php',
                'website_id' => '11',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '',
                'str_replace' => '',
                'replace_with' => '',
                'append_str' => '',
            ],

            [
                //  https://lojaonline.gonatural.pt/
                'main_listing_node' => '.grid__item.grid__item--collection-template.small--one-half.medium-up--one-fifth',
                'title' => '.product-card__title',
                'description' => '',
                'brand' => '',
                'price' => '.price-item.price-item--regular',
                'unit_price' => '',
                'discount' => '',
                'image' => 'img',
                'image_url' => 'https:',
                'rating' => '',
                'product_link' => '.grid-view-item__link',
                'product_url' => 'https://lojaonline.gonatural.pt/',
                'website_id' => '12',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '?',
                'str_replace' => '{width}',
                'replace_with' => '360',
                'append_str' => '',
            ],
            [
                //  https://www.aldi.pt/
                'main_listing_node' => '.col-xs-6.col-sm-4.col-lg-3',
                'title' => '.mod-article-tile__action',
                'description' => '.mod-article-tile__content p',
                'brand' => '',
                'price' => '.price__main',
                'unit_price' => '',
                'discount' => '.price--right .price__previous-percentage',
                'image' => 'img',
                'image_url' => 'https://www.aldi.pt',
                'rating' => '',
                'product_link' => '.mod-article-tile__action',
                'product_url' => '',
                'website_id' => '13',
                'last_updated' => '',
                'substr' => '',
                'explode' => ',',
                'substr_strpos' => '/jcr',
                'str_replace' => '',
                'replace_with' => '',
                'append_str' => '',
            ],
            [
                // https://lojaonline.minipreco.pt/
                'main_listing_node' => '.span-3',
                'title' => '.prod_grid .details',
                'description' => '',
                'brand' => '',
                'price' => '.prod_grid .cart .price_container p',
                'unit_price' => '.prod_grid .cart .price_container .pricePerKilogram',
                'discount' => '.price--right .price__previous-percentage',
                'image' => 'img',
                'image_url' => '',
                'rating' => '',
                'product_link' => '.prod_grid .productMainLink',
                'product_url' => 'https://lojaonline.minipreco.pt/',
                'website_id' => '14',
                'last_updated' => '',
                'substr' => '',
                'explode' => '',
                'substr_strpos' => '',
                'str_replace' => '',
                'replace_with' => '',
                'append_str' => '',
            ],

            [
                // https://www.amazon.com/ref=nav_logo
                'main_listing_node' => '.sg-col-4-of-12',
                'title' => 'h2.a-size-mini',
                'description' => '',
                'brand' => '',
                'price' => '.a-price[data-a-size=l]',
                'unit_price' => '',
                'discount' => '',
                'image' => '.s-image',
                'image_url' => '',
                'rating' => 'h2.a-size-mini',
                'product_link' => '.a-link-normal.s-no-outline',
                'product_url' => 'https://www.amazon.com/',
                'website_id' => '16',
                'last_updated' => '',
                'substr' => '',
                'explode' => ',',
                'substr_strpos' => '',
                'str_replace' => '3x',
                'replace_with' => '',
                'append_str' => '',
            ],
        ];
        DB::table('product_nodes')->insert($product_nodes);
    }
}
